name: Check Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Verify Calendar Secret Exists
        run: |
          if [ -z "${{ secrets.GOOGLE_CALENDAR_ID }}" ]; then
            echo "GOOGLE_CALENDAR_ID missing"
            exit 1
          fi

          echo "GOOGLE_CALENDAR_ID found"

      - name: Verify Credentials Secret Exists
        run: |
          if [ -z "${{ secrets.GOOGLE_CREDENTIALS }}" ]; then
            echo "GOOGLE_CREDENTIALS missing"
            exit 1
          fi

          echo "GOOGLE_CREDENTIALS found"
