name: Brunswick Event Test

on:
  workflow_dispatch:

  schedule:
    - cron: '0 10 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Run Brunswick Import Test
        shell: pwsh
        run: ./scripts/Get-BrunswickEvents.ps1

      - name: Commit events.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add events.json

          git diff --staged --quiet || git commit -m "Update events.json"

          git push
