name: Calendar Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Google Calendar Test
        shell: pwsh
        run: ./scripts/Create-GoogleCalendarEvents.ps1
