      - name: Show Coastal Events JSON
        run: |
          cat coastal_events.json

      - name: Commit Coastal Events
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add coastal_events.json

          git diff --staged --quiet || git commit -m "Update coastal events"

          git push
